### ISSUE TITLE
Debian/Ubuntu packaging 

### ISSUE THREAD

**Issue by evilaliv3** [bmuller/twistar#61]
While working on GlobaLeaks and evaluating twistar usage (globaleaks/GlobaLeaks#1551) we are now evaluating to provide support on debian packaging of twistar in order too speed up the possibility to have it both in debian stretch and ubuntu xenial.

This ticket is to keep track of the activities related activities

https://lists.debian.org/debian-python/2015/10/msg00267.html

@bmuller: are you already following this activities?

\cc @fpietrosanti

**Comment by bmuller** [comment]
@evilaliv3 I'm not following.  Packaging for various distros is entirely up to those distros - this repo (and issue tracker) is solely for the python library.  Feel free to open individual tickets if there are issues relating to the library.  Thanks!

**Comment by fpietrosanti** [comment]
@bmuller the packaging meta-data and configuration files are usually part of the code-base and kept on the library git repository, see https://wiki.debian.org/Python/Packaging and https://wiki.debian.org/Python/LibraryStyleGuide for further informations.

Example of outcome are like for Cyclone for Twisted https://github.com/fiorix/cyclone/tree/master/debian .

That facilitate a lot the maintenance of the software and the inclusion into linux distribution, for greater uses, we'd love to help with that if we'll migrate from Storm to Twistar for a new ORM, as GlobaLeaks need to be included into the debian repositories, so it's dependencies

**Comment by bmuller** [comment]
@fpietrosanti I think that's uncommon to have folders in the root of a Python repo for every distro that needs one.  I'd be happy to add a branch, though, named `debian` that has those files.  The [Twisted repo](https://twistedmatrix.com/trac/browser) does something similar in that they don't include the debian config in the trunk, but rather in another top level folder.

**Comment by evilaliv3** [comment]
the only benefit of having it in the same repo is the simplicity to sign it all at one when you release a package version, but this is up to you :)

**Comment by evilaliv3** [comment]
@bmuller: messages in this thread should be of your interest https://lists.debian.org/debian-python/2016/01/msg00013.html

**Comment by bmuller** [comment]
```
I'm not sure twistar is in better shape, given that the last PyPI release is 2013.
```
It's still alive!

**Comment by evilaliv3** [comment]
hahahah

by the way it would be great to fix together the few python3 errors so to be ready for ubuntu 16.04

i will try to support you as much that i can

**Comment by bmuller** [comment]
So, it looks like `twisted.enterprise` hasn't yet been ported to python 3, and `twisted.enterprise.adbapi` is necessary for all of `twistar` to work.

**Comment by evilaliv3** [comment]
it will! in twisted we trust!
