### ISSUE TITLE
How to make a join statement

### ISSUE THREAD

**Issue by aaleotti-unimore** [bmuller/twistar#72]
Hi, I read the documentation but there's no sign how to make a join statement (or using implicit notation, select from two different tables using a where clause). is there a proper way rather than directly with low level sql statements?

**Comment by bmuller** [comment]
http://findingscience.com/twistar/doc/relationship_examples.html

**Comment by aaleotti-unimore** [comment]
so there's no way to make a relationship that's not based on the id colum of a table?

**Comment by bmuller** [comment]
I think you can specify the join columns

**Comment by aaleotti-unimore** [comment]
can you tell where it's explained? because it's not specified anywhere which are the acceptable arguments for the optional dictionary of the HASONE / HASMANY / etc class variables
The example only says to refer to the Relationships class but in the docs there's nothing to define the columns.

I used the line as shown in the example: 

```
class Comment(DBObject):
     HASONE = [{'name': 'User', 'class_name': 'user', foreign_key: 'user_id'}]

class User(DBObject):
     pass
```

but I can't specify which is the column in the Comment class i want to join in the User class (named user_id as well)

Thanks for your support
